apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::060699023193:role/eksctl-mahi-cluster-nodegroup-stan-NodeInstanceRole-Rb1F094IJ1xo
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      # Notice I removed "service-role/" below
      rolearn: arn:aws:iam::060699023193:role/codebuild-mahi-tasks-final-build-service-role
      username: codebuild
