version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv ./kubectl /usr/local/bin/kubectl

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 060699023193.dkr.ecr.us-east-1.amazonaws.com
      - echo "Connecting to EKS Cluster..."
      - aws eks update-kubeconfig --name mahi-cluster --region us-east-1
      - kubectl get nodes

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t mahi-tasks-app .
      - docker tag mahi-tasks-app:latest 060699023193.dkr.ecr.us-east-1.amazonaws.com/mahi-tasks-app:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 060699023193.dkr.ecr.us-east-1.amazonaws.com/mahi-tasks-app:latest
      - echo "Deploying to EKS..."
      - kubectl apply -f deployment.yaml --validate=false
      - kubectl apply -f service.yaml --validate=false
      - echo "Deployment Complete!"

artifacts:
  files: 
    - deployment.yaml
    - service.yaml
