apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mahi-app
  template:
    metadata:
      labels:
        app: mahi-app
    spec:
      containers:
      - name: mahi-app-container
        image: 060699023193.dkr.ecr.us-east-1.amazonaws.com/mahi-tasks-app:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mahi-app-service
spec:
  type: LoadBalancer
  selector:
    app: mahi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
